apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: web-app-pipeline-run
spec:
  pipelineRef:
    name: web-app-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
